### ISSUE TITLE
web启动硬件加速问题

### ISSUE THREAD

**Issue by wjcspirit** [sunfusheng/Bingo#1]
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
        webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null); //启动硬件加速
}

应该是关闭硬件加速吧,硬件加速和软件加速是互斥的

**Comment by sunfusheng** [comment]
我改成下面这样啦，谢谢你
// >= 19(SDK4.4)启动硬件加速，否则启动软件加速
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
    webView.setLayerType(View.LAYER_TYPE_HARDWARE, null);
} else {
    webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
}

**Comment by wyh497823256** [comment]
学习一下。
